# Generated by Django 4.1.2 on 2022-10-17 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0002_config_alter_card_fio_alter_card_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'agreed'), (1, 'onchecking'), (2, 'rejected'), (3, 'default')], default=3),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
