# Generated by Django 4.1.2 on 2022-10-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0003_card_created_at_card_status_card_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
