# Generated by Django 3.2.16 on 2022-10-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0005_card_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='passport',
            field=models.FileField(blank=True, default='', null=True, upload_to='passports/', verbose_name='Паспорт'),
        ),
    ]
